# Generated by Django 6.1 on 2026-09-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About ASOK', max_length=200)),
                ('short_description', models.TextField(help_text='Short description for the homepage.')),
                ('full_description', models.TextField(help_text='Main organization description.')),
                ('mission', models.TextField(help_text='Organization mission.')),
                ('vision', models.TextField(help_text='Organization vision.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='organization/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization Information',
                'verbose_name_plural': 'Organization Information',
            },
        ),
    ]
