# Generated by Django 6.1 on 2026-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationinfo',
            options={},
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='address',
            field=models.CharField(blank=True, help_text='Office address.', max_length=300),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='email',
            field=models.EmailField(default='info@asok.info', help_text='Official organization email.', max_length=254),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Official Facebook page URL.'),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Official LinkedIn page URL.'),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='phone',
            field=models.CharField(blank=True, help_text='Official phone number.', max_length=30),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Official YouTube channel URL.'),
        ),
    ]
