# Generated by Django 6.1 on 2026-09-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('membership_type', models.CharField(choices=[('volunteer', 'Volunteer'), ('member', 'General Member'), ('student', 'Student Volunteer'), ('professional', 'Professional Member')], default='volunteer', max_length=20)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(max_length=300)),
                ('area_of_interest', models.CharField(choices=[('human_rights', 'Human Rights'), ('legal_aid', 'Legal Aid'), ('awareness', 'Awareness Campaign'), ('community', 'Community Development'), ('research', 'Research'), ('training', 'Training & Workshop'), ('other', 'Other')], max_length=30)),
                ('motivation', models.TextField(help_text='Why do you want to join ASOK Foundation?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Application',
                'verbose_name_plural': 'Membership Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
