# Generated by Django 6.1 on 2026-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='birth_registration_number',
            field=models.CharField(blank=True, help_text='Birth Registration number.', max_length=30),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='nid_number',
            field=models.CharField(blank=True, help_text='National ID (NID) number.', max_length=30),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='photo',
            field=models.ImageField(blank=True, help_text="Member's recent passport-size photo.", null=True, upload_to='membership/photos/'),
        ),
    ]
