# Generated by Django 6.1 on 2026-09-11 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membershipapplication_birth_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('registration', 'Registration Fee'), ('monthly', 'Monthly Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=20)),
                ('payment_month', models.DateField(blank=True, help_text='For monthly fee, select the month this payment covers.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='bKash/Nagad/Bank transaction ID if applicable.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='membership.membershipapplication')),
            ],
            options={
                'verbose_name': 'Membership Payment',
                'verbose_name_plural': 'Membership Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
