# Generated by Django 6.1 on 2026-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_membershippayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=1000, help_text='One-time registration fee.', max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=100, help_text='Monthly membership fee.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Fee Settings',
                'verbose_name_plural': 'Membership Fee Settings',
            },
        ),
    ]
