# Generated by Django 6.1 on 2026-09-11 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='New position or designation.', max_length=150)),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this promotion.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='membership.member')),
            ],
            options={
                'verbose_name': 'Member Promotion',
                'verbose_name_plural': 'Member Promotions',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
