# Generated by Django 5.2.17 on 2026-10-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_memberpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name="Father's Name"),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='identity_document',
            field=models.ImageField(blank=True, help_text='Upload a clear image of NID or Birth Registration document.', null=True, upload_to='membership/identity_documents/', verbose_name='NID / Birth Registration Image'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name="Mother's Name"),
        ),
    ]
