# Generated by Django 5.2.17 on 2026-10-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_member_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershippayment',
            options={'ordering': ['-payment_month', '-created_at']},
        ),
    ]
