# Generated by Django 5.2.17 on 2026-10-10 01:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_alter_membershippayment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='activation_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
