# Generated by Django 6.1 on 2026-09-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('category', models.CharField(choices=[('human_rights', 'Human Rights'), ('legal_aid', 'Legal Aid'), ('awareness', 'Awareness'), ('community', 'Community Development'), ('training', 'Training & Workshop'), ('research', 'Research'), ('other', 'Other')], default='human_rights', max_length=30)),
                ('short_description', models.TextField(help_text='Short description shown on activity cards.', max_length=500)),
                ('description', models.TextField(help_text='Full activity/project description.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('location', models.CharField(blank=True, max_length=250)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('beneficiaries', models.PositiveIntegerField(default=0, help_text='Approximate number of people benefited.')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming')], default='upcoming', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this activity on the homepage.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number appears first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['order', '-start_date', '-created_at'],
            },
        ),
    ]
