# Generated by Django 6.1 on 2026-09-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Example: People Reached', max_length=100)),
                ('value', models.PositiveIntegerField(default=0, help_text='Example: 500')),
                ('suffix', models.CharField(blank=True, default='+', help_text='Example: +, %, K', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(default='users', help_text='Icon identifier for frontend.', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impact Statistic',
                'verbose_name_plural': 'Impact Statistics',
                'ordering': ['order', 'id'],
            },
        ),
    ]
