# Generated by Django 5.2.17 on 2026-09-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_impactstatistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
