# Generated by Django 5.2.17 on 2026-10-02 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_membershipapplication_father_name_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_type', models.CharField(choices=[('central', 'Central Committee'), ('division', 'Division Committee'), ('district', 'District Committee'), ('metropolitan', 'Metropolitan Committee'), ('thana_upazila', 'Thana / Upazila Committee'), ('municipality', 'Municipality Committee'), ('union_ward', 'Union / Ward Committee')], max_length=30)),
                ('member_type', models.CharField(choices=[('member', 'Committee Member'), ('advisor', 'Advisory Council')], default='member', max_length=20)),
                ('designation', models.CharField(choices=[('president', 'সভাপতি'), ('senior_vice_president', 'সিনিয়র সহ-সভাপতি'), ('vice_president', 'সহ-সভাপতি'), ('general_secretary', 'সাধারণ সম্পাদক'), ('joint_general_secretary', 'যুগ্ম সাধারণ সম্পাদক'), ('organizing_secretary', 'সাংগঠনিক সম্পাদক'), ('assistant_organizing_secretary', 'সহ সাংগঠনিক সম্পাদক'), ('sontro_secretary', 'সন্ত্র সম্পাদক'), ('assistant_sontro_secretary', 'সহ সন্ত্র সম্পাদক'), ('publicity_secretary', 'প্রচার সম্পাদক'), ('assistant_publicity_secretary', 'সহ-প্রচার সম্পাদক'), ('finance_secretary', 'অর্থ সম্পাদক'), ('religious_affairs_secretary', 'ধর্ম বিষয়ক সম্পাদক'), ('assistant_religious_affairs_secretary', 'সহ ধর্ম বিষয়ক সম্পাদক'), ('it_secretary', 'তথ্য ও প্রযুক্তি বিষয়ক সম্পাদক'), ('assistant_it_secretary', 'সহ তথ্য ও প্রযুক্তি বিষয়ক সম্পাদক'), ('social_welfare_secretary', 'সমাজ কল্যাণ বিষয়ক সম্পাদক'), ('assistant_social_welfare_secretary', 'সহ সমাজ কল্যাণ বিষয়ক সম্পাদক'), ('human_rights_secretary', 'মানবাধিকার বিষয়ক সম্পাদক'), ('assistant_human_rights_secretary', 'সহ মানবাধিকার বিষয়ক সম্পাদক'), ('supervisory_secretary', 'তত্ত্বাবধায়ক সম্পাদক'), ('assistant_supervisory_secretary', 'সহ তত্ত্বাবধায়ক সম্পাদক'), ('housing_secretary', 'আবাসন বিষয়ক সম্পাদক'), ('assistant_housing_secretary', 'সহ আবাসন বিষয়ক সম্পাদক'), ('international_affairs_secretary', 'আন্তর্জাতিক বিষয়ক সম্পাদক'), ('assistant_international_affairs_secretary', 'সহ আন্তর্জাতিক বিষয়ক সম্পাদক'), ('relief_rehabilitation_secretary', 'ত্রাণ ও পুনর্বাসন বিষয়ক সম্পাদক'), ('assistant_relief_rehabilitation_secretary', 'সহ ত্রাণ ও পুনর্বাসন বিষয়ক সম্পাদক'), ('press_publication_secretary', 'প্রেস ও প্রকাশনা বিষয়ক সম্পাদক'), ('assistant_press_publication_secretary', 'সহ প্রেস ও প্রকাশনা বিষয়ক সম্পাদক'), ('reception_secretary', 'আপ্যায়ন বিষয়ক সম্পাদক'), ('assistant_reception_secretary', 'সহ আপ্যায়ন বিষয়ক সম্পাদক'), ('media_secretary', 'মিডিয়া বিষয়ক সম্পাদক'), ('assistant_media_secretary', 'সহ মিডিয়া বিষয়ক সম্পাদক'), ('education_secretary', 'শিক্ষা বিষয়ক সম্পাদক'), ('assistant_education_secretary', 'সহ শিক্ষা বিষয়ক সম্পাদক'), ('health_secretary', 'স্বাস্থ্য বিষয়ক সম্পাদক'), ('assistant_health_secretary', 'সহ স্বাস্থ্য বিষয়ক সম্পাদক'), ('medical_activist', 'চিকিৎসা-অভিনেত্রী'), ('sports_secretary', 'ক্রীড়া বিষয়ক সম্পাদক'), ('women_children_secretary', 'মহিলা ও শিশু বিষয়ক সম্পাদক'), ('assistant_women_children_secretary', 'সহ মহিলা ও শিশু বিষয়ক সম্পাদক'), ('intellectual_sports_secretary', 'বুদ্ধ ও ক্রীড়া বিষয়ক সম্পাদক'), ('assistant_intellectual_sports_secretary', 'সহ বুদ্ধ ও ক্রীড়া বিষয়ক সম্পাদক'), ('executive_member', 'নির্বাহী সদস্য'), ('member', 'সদস্য')], default='member', max_length=60)),
                ('division', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('thana_upazila', models.CharField(blank=True, max_length=100)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('union_ward', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=150)),
                ('post_office', models.CharField(blank=True, max_length=150)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_positions', to='membership.member')),
            ],
            options={
                'verbose_name': 'Committee Member',
                'verbose_name_plural': 'Committee Members',
                'ordering': ['committee_type', 'designation', 'member__application__full_name'],
            },
        ),
    ]
