# Generated by Django 5.2.17 on 2026-10-02 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_division_district_upazila_unionward_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_members', to='team.district'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_members', to='team.division'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_members', to='team.municipality'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='thana_upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_members', to='team.upazila'),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='union_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_members', to='team.unionward'),
        ),
    ]
