# Generated by Django 5.2.17 on 2026-10-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_committeemember_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMinimum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_type', models.CharField(choices=[('central', 'Central Committee'), ('division', 'Division Committee'), ('district', 'District Committee'), ('metropolitan', 'Metropolitan Committee'), ('thana_upazila', 'Thana / Upazila Committee'), ('municipality', 'Municipality Committee'), ('union_ward', 'Union / Ward Committee')], max_length=30, unique=True)),
                ('minimum_members', models.PositiveIntegerField(default=0, help_text='Minimum number of members required for this committee.')),
            ],
            options={
                'verbose_name': 'Committee Minimum',
                'verbose_name_plural': 'Committee Minimums',
                'ordering': ['committee_type'],
            },
        ),
    ]
