# Generated by Django 6.1 on 2026-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=25, unique=True)),
                ('donor_name', models.CharField(blank=True, help_text='Leave blank if the donor wants to remain anonymous.', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(choices=[('general', 'General Support'), ('human_rights', 'Human Rights'), ('legal_aid', 'Legal Aid'), ('community', 'Community Development'), ('awareness', 'Awareness Programs'), ('other', 'Other')], default='general', max_length=30)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('cash', 'Cash'), ('other', 'Other')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment transaction ID, if available.', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from the donor.')),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
