# Generated by Django 6.1 on 2026-09-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('complainant_name', models.CharField(blank=True, help_text='Leave blank if you want to remain anonymous.', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(choices=[('violence', 'Violence or Abuse'), ('discrimination', 'Discrimination'), ('harassment', 'Harassment'), ('land', 'Land or Property'), ('employment', 'Employment'), ('family', 'Family Matter'), ('other', 'Other')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField()),
                ('preferred_contact', models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email')], max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='submitted', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
